manifest:
  projects:
    - name: zmk
      url: https://github.com/zmkfirmware/zmk.git
      revision: main
      west-commands: scripts/west-commands.yml
      import: app/west.yml  # Loads the main ZMK config
  self:
    path: config
